version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "22"
  jobs:
    install:
      - pip install .
    post_install:
      # Import matplotlib to build the font cache.
      # Otherwise, the first time it's imported cell execution can timeout.
      - python -c "import matplotlib"
    build:
      html:
        - cd book/ && jupyter book build --ci --html --execute
        - mkdir -p $READTHEDOCS_OUTPUT
        - mv ./book/_build/html $READTHEDOCS_OUTPUT