version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    install:
      # Install uv
      - pip install uv
      # Sync dependencies from pyproject.toml/requirements.txt
      - uv sync
      # Download and install Quarto CLI
      - wget "https://github.com/quarto-dev/quarto-cli/releases/download/v1.7.32/quarto-1.7.32-linux-amd64.tar.gz"
      - mkdir -p ~/opt && tar -C ~/opt -xvzf quarto*.tar.gz
      - mkdir -p ~/bin && ln -s ~/opt/quarto-1.7.32/bin/quarto ~/bin/quarto
    post_install:
      # Pre-build matplotlib font cache
      - uv run python -c "import matplotlib"
    build:
      html:
        # Build the Quarto book using uv run
        - uv run ~/bin/quarto render
        # Ensure output directory exists and move built files
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - mv _book/* $READTHEDOCS_OUTPUT/html/.
