project:
  type: book

book:
  title: "Animals In Motion"
  author:
    - Niko Sirmpilatze
    - Sofía Miñano
    - Chang Huan Lo
  date: "2025-08-11"
  chapters:
    - index.qmd
    - intro.qmd
    - neural-networks.qmd
    - sleap-tutorial.qmd
    - movement-tutorial.qmd
    - references.qmd

bibliography: references.bib

# Explicitly disable PDF rendering
pdf: false

format:
  html:
    theme:
      - cosmo
      - brand



