channels:
  - conda-forge
dependencies:
  - movement>=0.8.1
  - napari<0.6.3
  - pyqt
  - jupyter
  - python>3.11
  - pip
  # Tools for development
  - pre-commit
  - ruff
  - codespell
  - jupyter-cache
