project:
  type: book
  resources:
    - "*.ipynb"  # Include jupyter notebooks in the rendered book

book:
  title: "Animals In Motion"
  author:
    - Niko Sirmpilatze
    - Sofía Miñano
    - Chang Huan Lo
  date: today
  date-format: long
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-neural-networks.qmd
    - 03-sleap-tutorial.qmd
    - 04-movement-mouse.ipynb
    - 05-movement-zebras.qmd
  appendices:
    - prerequisites.qmd
    - contributing.qmd
    - references.qmd
  page-footer: "This website is made with [Quarto Book](https://quarto.org/docs/books), see @sec-contributing." 
  # Options for GitHub repository links
  repo-url: https://github.com/neuroinformatics-unit/animals-in-motion
  repo-subdir: book
  repo-actions: [edit, source, issue]
  repo-link-target: _blank  # open in new tab

bibliography: references.bib

# Explicitly disable PDF rendering
pdf: false

format:
  html:
    theme:
      - cosmo
      - brand


# Options for code execution: https://quarto.org/docs/computations/caching.html
execute: 
  cache: true
jupyter: python3
