project:
  type: book

book:
  title: "Animals In Motion"
  author:
    - Niko Sirmpilatze
    - Sofía Miñano
    - Chang Huan Lo
  date: today
  date-format: long
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-neural-networks.qmd
    - 03-sleap-tutorial.qmd
    - 04-movement-mouse.qmd
    - 05-movement-zebras.qmd
  appendices:
    - prerequisites.qmd
    - contributing.qmd
    - references.qmd

bibliography: references.bib

# Explicitly disable PDF rendering
pdf: false

format:
  html:
    theme:
      - cosmo
      - brand



