name: Publish to GitHub Pages

on:
    push:
      branches: [main]
      tags: ['*']
    pull_request:
    workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: neuroinformatics-unit/actions/lint@v2
  build:
    name: render and publish
    runs-on: ubuntu-latest
    needs: linting
    permissions:
      contents: write          # push to gh‑pages
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: |
          uv sync --locked --all-extras

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # 👇 single step that both renders and deploys to the gh‑pages branch
      - name: Render and publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
