name: Publish

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    if: (github.event_name == 'schedule' && github.repository_owner == 'neuroinformatics' && github.ref == 'refs/heads/main') ||
        (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - uses: neuroinformatics-unit/actions/lint@v2
  
  build:
    name: render and publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  